### ISSUE TITLE
It covers tests files in calculation.

### ISSUE THREAD

**Issue by paritoshraval100** [mattpolzin/swift-codecov-action#3]
Overall Coverage: 84.21%

File                   Coverage
---------------------- --------
File1.swift         66.67%  
File2.swift      50.00%  
                               
=-=-=-=-=-=-=-=-=              
                               
**File1Tests.swift    100.00% 
File2Tests.swift 100.00%**

**Comment by mattpolzin** [comment]
version `0.7.1` should take care of this.

There are now two new options for the action:
`INCLUDE_TESTS` and `INCLUDE_DEPENDENCIES`. Both default to false, so if the goal is _not_ to include dependencies or tests in coverage numbers, they can be omitted.
