### ISSUE TITLE
The `set-output` command is deprecated

### ISSUE THREAD

**Issue by dabrahams** [mattpolzin/swift-codecov-action#7]
Nice plugin!  It's generating this warning though:

Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by mattpolzin** [comment]
Indeed. Thanks for creating a ticket for it. Easy enough change, just waiting to get a newer version of the underlying tool built and pushed to Docker Hub before merging and releasing the fix for the action.

**Comment by dabrahams** [comment]
Just want to say, I love the way you treat me as a contributor when I file issues; that is by no means universal. Thanks!
